package option

// ----------------------------------------------------------------------------
// Constants
// ----------------------------------------------------------------------------

const (
	ConfigPath                = "config-path"
	Configuration             = "configuration"
	DatabaseUrl               = "database-url"
	Datasources               = "datasources"
	DelayInSeconds            = "delay-in-seconds"
	EnableAll                 = "enable-all"
	EnableG2config            = "enable-g2config"
	EnableG2configmgr         = "enable-g2configmgr"
	EnableG2diagnostic        = "enable-g2diagnostic"
	EnableG2engine            = "enable-g2engine"
	EnableG2product           = "enable-g2product"
	EnableSenzingChatApi      = "enable-senzing-chat-api"
	EnableSenzingRestApi      = "enable-senzing-rest-api"
	EnableSwaggerUi           = "enable-swagger-ui"
	EnableXterm               = "enable-xterm"
	EngineConfigurationJson   = "engine-configuration-json"
	EngineLogLevel            = "engine-log-level"
	EngineModuleName          = "engine-module-name"
	GrpcPort                  = "grpc-port"
	GrpcUrl                   = "grpc-url"
	HttpPort                  = "http-port"
	InputFileType             = "input-file-type"
	InputURL                  = "input-url"
	LicenseStringBase64       = "license-string-base64"
	LogLevel                  = "log-level"
	MonitoringPeriodInSeconds = "monitoring-period-in-seconds"
	NumberOfWorkers           = "number-of-workers"
	ObserverOrigin            = "observer-origin"
	ObserverUrl               = "observer-url"
	OutputURL                 = "output-url"
	RecordMax                 = "record-max"
	RecordMin                 = "record-min"
	RecordMonitor             = "record-monitor"
	ResourcePath              = "resource-path"
	SenzingDirectory          = "senzing-directory"
	ServerAddress             = "server-address"
	SupportPath               = "support-path"
	VisibilityPeriodInSeconds = "visibility-period-in-seconds"
	XtermAllowedHostnames     = "xterm-allowed-hostnames"
	XtermArguments            = "xterm-arguments"
	XtermCommand              = "xterm-command"
	XtermConnectionErrorLimit = "xterm-connection-error-limit"
	XtermKeepalivePingTimeout = "xterm-keepalive-ping-timeout"
	XtermMaxBufferSizeBytes   = "xterm-max-buffer-size-bytes"
)
