name: go test linux

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

permissions:
  contents: read

jobs:
  go-test-linux:
    name: "go test with Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
        senzingapi-version: [latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v1
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - run: mkdir /tmp/sqlite

      - run: touch /tmp/sqlite/G2C.db

      - name: run go test
        run: go test -v -p 1 ./...
