name: Govulncheck

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:

  sdk-versions:
    runs-on: ubuntu-latest
    outputs:
      senzingsdk-versions: ${{ steps.cfg.outputs.senzingsdk-versions }}
    steps:
      - id: cfg
        uses: senzing-factory/build-resources/sdk-versions@v4
  govulncheck:
    needs: sdk-versions
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.26"]
        senzingsdk-version: ${{ fromJSON(needs.sdk-versions.outputs.senzingsdk-versions) }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v4
        with:
          senzingsdk-version: ${{ matrix.senzingsdk-version }}

      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go }}
