name: make github release assets linux

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  make-github-release-assets-linux:
    name: publish binaries - linux
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: make RPM/DEB files
        run: make package

      - name: upload versioned packages to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/senzing-tools-*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  slack-notification:
    needs: [make-github-release-assets-linux]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.make-github-release-assets-linux.outputs.status ) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.make-github-release-assets-linux.outputs.status }}
