name: make github release assets darwin

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  make-github-release-assets-darwin:
    name: publish binaries - darwin
    runs-on: macos-latest
    strategy:
      matrix:
        senzingsdk-version: ["staging-v4"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install create-dmg
        run: brew install create-dmg

      - name: install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v1
        with:
          senzingsdk-version: ${{ matrix.senzingsdk-version }}

      - name: make executable file
        run: make darwin/amd64

      - name: adjust create-dmg
        run: |
          sed -e "s|ln -s /Applications|ln -s /usr/local/bin|" /usr/local/bin/create-dmg > /usr/local/bin/create-dmg-new
          mv /usr/local/bin/create-dmg /usr/local/bin/create-dmg-backup
          mv /usr/local/bin/create-dmg-new /usr/local/bin/create-dmg
          chmod +x /usr/local/bin/create-dmg

      - name: make a .dmg file
        run: |
          BUILD_VERSION=$(git describe --always --tags --abbrev=0 --dirty  | sed 's/v//')
          create-dmg --app-drop-link 0 40 "senzing-tools-$BUILD_VERSION.dmg"  "target/darwin-amd64/"

      - name: upload versioned package to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/Users/runner/work/senzing-tools/senzing-tools/senzing-tools-*"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
