name: make github release assets darwin

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  make-github-release-assets-darwin:
    name: publish binaries - darwin
    outputs:
      status: ${{ job.status }}
    runs-on: macos-latest
    strategy:
      matrix:
        go: ["1.24"]
        senzingsdk-version: ["production-v4"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: install create-dmg
        run: brew install create-dmg

      - name: install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          senzingsdk-version: ${{ matrix.senzingsdk-version }}

      - name: Set environment variables
        run: |
          SENZING_PATH="${HOME}/senzing"
          {
            echo "SENZING_PATH=${SENZING_PATH}"
            echo "LD_LIBRARY_PATH=${SENZING_PATH}/er/lib:${SENZING_PATH}/er/lib/macos"
            echo "DYLD_LIBRARY_PATH=${SENZING_PATH}/er/lib:${SENZING_PATH}/er/lib/macos"
            echo  CGO_CFLAGS="-g -I${SENZING_PATH}/er/sdk/c"
            echo  CGO_LDFLAGS="-L${SENZING_PATH}/er/lib -lSz -Wl,-no_warn_duplicate_libraries"
          } >> "$GITHUB_ENV"

      - name: make executable file
        run: |
          go build -o "target/darwin-amd64/senzing-tools"

      - name: make a .dmg file
        run: |
          BUILD_VERSION=$(git describe --always --tags --abbrev=0 --dirty  | sed 's/v//')
          create-dmg --app-drop-link 0 40 "senzing-tools-$BUILD_VERSION.dmg"  "target/darwin-amd64/"

      - name: upload versioned package to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/Users/runner/work/senzing-tools/senzing-tools/senzing-tools-*"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  slack-notification:
    needs: [make-github-release-assets-darwin]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.make-github-release-assets-darwin.outputs.status ) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v3
    with:
      job-status: ${{ needs.make-github-release-assets-darwin.outputs.status }}
