name: make github release assets linux

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  make-github-release-assets-linux:
    name: publish binaries - linux
    outputs:
      status: ${{ job.status }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: make RPM/DEB files
        run: make package

      - name: upload versioned packages to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/senzing-tools-*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  slack-notification:
    needs: [make-github-release-assets-linux]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.make-github-release-assets-linux.outputs.status ) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v3
    with:
      job-status: ${{ needs.make-github-release-assets-linux.outputs.status }}
