name: make-github-release-assets-linux.yaml
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions: write-all
jobs:
  build:
    name: Publish binaries - linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make RPM/DEB files
        run: make package
      - name: List directories
        run: |
          pwd
          ls -la
          ls -la target/
      - name: Upload versioned packages to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/senzing-tools-*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
