name: spellcheck

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: streetsidesoftware/cspell-action@v7
        with:
          config: .vscode/cspell.json
